language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

services:
  - memcached
  - mysql
  - postgresql

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'CREATE DATABASE test;' -U postgres
  - psql -c "CREATE USER test WITH PASSWORD '123';" -U postgres
  - travis_retry composer self-update

install:
  - travis_retry composer install -n

script: vendor/bin/phpunit
